name: quill_delta_dart
description: Simple and expressive format for describing rich-text content created for Quill.js editor. This package is unofficial port to Dart from JavaScript.
version: 1.0.2-a.1
homepage: https://github.com/volser/quill-delta-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  collection: ^1.14.5
  quiver_hashcode: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  test_coverage: ^0.4.1
  pedantic: ^1.9.0
